2025-05-30 19:05:19,856 INFO    MainThread:1600690 [wandb_setup.py:_flush():67] Current SDK version is 0.19.8
2025-05-30 19:05:19,856 INFO    MainThread:1600690 [wandb_setup.py:_flush():67] Configure stats pid to 1600690
2025-05-30 19:05:19,856 INFO    MainThread:1600690 [wandb_setup.py:_flush():67] Loading settings from /home/ouyangzl/.config/wandb/settings
2025-05-30 19:05:19,857 INFO    MainThread:1600690 [wandb_setup.py:_flush():67] Loading settings from /home/ouyangzl/BaseLine/3 NN/wandb/settings
2025-05-30 19:05:19,857 INFO    MainThread:1600690 [wandb_setup.py:_flush():67] Loading settings from environment variables
2025-05-30 19:05:19,857 INFO    MainThread:1600690 [wandb_init.py:setup_run_log_directory():647] Logging user logs to /home/ouyangzl/BaseLine/3 NN/wandb/run-20250530_190519-slrev9qa/logs/debug.log
2025-05-30 19:05:19,857 INFO    MainThread:1600690 [wandb_init.py:setup_run_log_directory():648] Logging internal logs to /home/ouyangzl/BaseLine/3 NN/wandb/run-20250530_190519-slrev9qa/logs/debug-internal.log
2025-05-30 19:05:19,857 INFO    MainThread:1600690 [wandb_init.py:init():761] calling init triggers
2025-05-30 19:05:19,857 INFO    MainThread:1600690 [wandb_init.py:init():766] wandb.init called with sweep_config: {}
config: {'_wandb': {}}
2025-05-30 19:05:19,857 INFO    MainThread:1600690 [wandb_init.py:init():784] starting backend
2025-05-30 19:05:19,857 INFO    MainThread:1600690 [wandb_init.py:init():788] sending inform_init request
2025-05-30 19:05:19,894 INFO    MainThread:1600690 [backend.py:_multiprocessing_setup():101] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2025-05-30 19:05:19,895 INFO    MainThread:1600690 [wandb_init.py:init():798] backend started and connected
2025-05-30 19:05:19,901 INFO    MainThread:1600690 [wandb_init.py:init():891] updated telemetry
2025-05-30 19:05:19,943 INFO    MainThread:1600690 [wandb_init.py:init():915] communicating run to backend with 90.0 second timeout
2025-05-30 19:05:20,609 INFO    MainThread:1600690 [wandb_init.py:init():990] starting run threads in backend
2025-05-30 19:05:20,724 INFO    MainThread:1600690 [wandb_run.py:_console_start():2375] atexit reg
2025-05-30 19:05:20,725 INFO    MainThread:1600690 [wandb_run.py:_redirect():2227] redirect: wrap_raw
2025-05-30 19:05:20,727 INFO    MainThread:1600690 [wandb_run.py:_redirect():2292] Wrapping output streams.
2025-05-30 19:05:20,728 INFO    MainThread:1600690 [wandb_run.py:_redirect():2315] Redirects installed.
2025-05-30 19:05:20,729 INFO    MainThread:1600690 [wandb_init.py:init():1032] run started, returning control to user process
2025-05-30 19:05:20,729 INFO    MainThread:1600690 [wandb_run.py:_config_callback():1261] config_cb None None {'np_seed': 12138, 'torch_seed': 12138, 'learning_rate': 1.0, 'steps': 500, 'record_steps': [5, 10, 15, 50, 100, 150, 200, 350, 500], 'input_dim': 16, 'hidden_dim': 32, 'output_dim': 10, 'variance': 0.01, 'top_k_pca_number': 50, 'rank': 7, 'wandb_project_name': 'Baseline', 'wandb_run_name': '3NN+GD+without activate function+traditional loss'}
2025-05-30 19:05:20,730 INFO    MainThread:1600690 [wandb_run.py:_config_callback():1261] config_cb None None {'eigenvalue_interval': 10, 'eigenvalue_type': 'raw_unnormalized', 'target_rank': 7, 'matrix_type': 'low_rank_identity'}
2025-05-30 22:36:09,027 INFO    MainThread:1600690 [retry.py:__call__():175] Retry attempt failed:
Traceback (most recent call last):
  File "/home/ouyangzl/.conda/envs/Hessian/lib/python3.12/site-packages/urllib3/connectionpool.py", line 773, in urlopen
    self._prepare_proxy(conn)
  File "/home/ouyangzl/.conda/envs/Hessian/lib/python3.12/site-packages/urllib3/connectionpool.py", line 1042, in _prepare_proxy
    conn.connect()
  File "/home/ouyangzl/.conda/envs/Hessian/lib/python3.12/site-packages/urllib3/connection.py", line 721, in connect
    self._tunnel()
  File "/home/ouyangzl/.conda/envs/Hessian/lib/python3.12/http/client.py", line 952, in _tunnel
    (version, code, message) = response._read_status()
                               ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ouyangzl/.conda/envs/Hessian/lib/python3.12/http/client.py", line 285, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ouyangzl/.conda/envs/Hessian/lib/python3.12/socket.py", line 707, in readinto
    return self._sock.recv_into(b)
           ^^^^^^^^^^^^^^^^^^^^^^^
TimeoutError: timed out

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/ouyangzl/.conda/envs/Hessian/lib/python3.12/site-packages/requests/adapters.py", line 667, in send
    resp = conn.urlopen(
           ^^^^^^^^^^^^^
  File "/home/ouyangzl/.conda/envs/Hessian/lib/python3.12/site-packages/urllib3/connectionpool.py", line 841, in urlopen
    retries = retries.increment(
              ^^^^^^^^^^^^^^^^^^
  File "/home/ouyangzl/.conda/envs/Hessian/lib/python3.12/site-packages/urllib3/util/retry.py", line 474, in increment
    raise reraise(type(error), error, _stacktrace)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ouyangzl/.conda/envs/Hessian/lib/python3.12/site-packages/urllib3/util/util.py", line 39, in reraise
    raise value
  File "/home/ouyangzl/.conda/envs/Hessian/lib/python3.12/site-packages/urllib3/connectionpool.py", line 775, in urlopen
    self._raise_timeout(
  File "/home/ouyangzl/.conda/envs/Hessian/lib/python3.12/site-packages/urllib3/connectionpool.py", line 367, in _raise_timeout
    raise ReadTimeoutError(
urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='api.wandb.ai', port=443): Read timed out. (read timeout=20)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ouyangzl/.conda/envs/Hessian/lib/python3.12/site-packages/wandb/sdk/lib/retry.py", line 134, in __call__
    result = self._call_fn(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ouyangzl/.conda/envs/Hessian/lib/python3.12/site-packages/wandb/sdk/internal/internal_api.py", line 398, in execute
    return self.client.execute(*args, **kwargs)  # type: ignore
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ouyangzl/.conda/envs/Hessian/lib/python3.12/site-packages/wandb/vendor/gql-0.2.0/wandb_gql/client.py", line 52, in execute
    result = self._get_result(document, *args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ouyangzl/.conda/envs/Hessian/lib/python3.12/site-packages/wandb/vendor/gql-0.2.0/wandb_gql/client.py", line 60, in _get_result
    return self.transport.execute(document, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ouyangzl/.conda/envs/Hessian/lib/python3.12/site-packages/wandb/sdk/lib/gql_request.py", line 58, in execute
    request = self.session.post(self.url, **post_args)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ouyangzl/.conda/envs/Hessian/lib/python3.12/site-packages/requests/sessions.py", line 637, in post
    return self.request("POST", url, data=data, json=json, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ouyangzl/.conda/envs/Hessian/lib/python3.12/site-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ouyangzl/.conda/envs/Hessian/lib/python3.12/site-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ouyangzl/.conda/envs/Hessian/lib/python3.12/site-packages/requests/adapters.py", line 713, in send
    raise ReadTimeout(e, request=request)
requests.exceptions.ReadTimeout: HTTPSConnectionPool(host='api.wandb.ai', port=443): Read timed out. (read timeout=20)
2025-05-30 22:51:04,801 INFO    MainThread:1600690 [wandb_run.py:_finish():2112] finishing run bxl307-university-of-birmingham/Baseline/slrev9qa
2025-05-30 22:51:04,801 INFO    MainThread:1600690 [wandb_run.py:_atexit_cleanup():2340] got exitcode: 0
2025-05-30 22:51:04,801 INFO    MainThread:1600690 [wandb_run.py:_restore():2322] restore
2025-05-30 22:51:04,801 INFO    MainThread:1600690 [wandb_run.py:_restore():2328] restore done
2025-05-30 22:51:06,952 INFO    MainThread:1600690 [wandb_run.py:_footer_history_summary_info():3956] rendering history
2025-05-30 22:51:06,960 INFO    MainThread:1600690 [wandb_run.py:_footer_history_summary_info():3988] rendering summary
2025-05-30 22:51:06,961 INFO    MainThread:1600690 [wandb_run.py:_footer_sync_info():3917] logging synced files
